{% set name = "positional" %}
{% set version = "1.2.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "cf48ea169f6c39486d5efa0ce7126a97bed979a52af6261cf255a41f9a74453a" %}
{% set build = 2 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - pbr >=1.8

  run:
    - python >={{ python_min }}
    - pbr >=1.8
    - wrapt

test:
  requires:
    - python {{ python_min }}
  imports:
    - positional

about:
  home: https://github.com/morganfainberg/positional
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Library to enforce positional or key-word arguments'

extra:
  recipe-maintainers:
    - pmlandwehr
    - morganfainberg
